# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integer2c <- function(number_r, conv_t) {
    .Call(`_cnum_integer2c`, number_r, conv_t)
}

integer2c_literal <- function(number_r, conv_t) {
    .Call(`_cnum_integer2c_literal`, number_r, conv_t)
}

